gbre_app/config/routes.rb
Rails.application.routes.draw do

  root 'listings#home'

  resources :listings

  devise_for :users
  
end


# Prefix Verb   URI Pattern                  Controller#Action
#     listings GET    /listings(.:format)          listings#index
#              POST   /listings(.:format)          listings#create
#  new_listing GET    /listings/new(.:format)      listings#new
# edit_listing GET    /listings/:id/edit(.:format) listings#edit
#      listing GET    /listings/:id(.:format)      listings#show
#              PATCH  /listings/:id(.:format)      listings#update
#              PUT    /listings/:id(.:format)      listings#update
#              DELETE /listings/:id(.:format)      listings#destroy

gbre_app/app/models/agent.rb
# class Agent < ActiveRecord::Base
# 	has_many :listings
# end

gbre_app/app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :agents

	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100#" }, default_url: "default.jpg"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

gbre_app/app/models/user.rb
class User < ActiveRecord::Base
  has_many :listings
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

gbre_app/app/controllers/agents_controller.rb
class AgentsController < ApplicationController
end

gbre_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, except: [:home]
end

gbre_app/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :set_listing, only: [:show, :edit, :update, :destroy]

	def index
		@listings = Listing.all
	end

	def show
		@listing = Listing.find(params[:id])
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = Listing.new(listing_params)
			@listings.save
			redirect_to listings_path
	end

	def edit
		@listing = Listing.find(params[:id])
	end

	def update
		if @listing.update(listing_params)
			redirect_to listings_path
		else
			render :edit
		end
	end

	def destroy
		@listing.destroy
		redirect_to listings_url
	end

	def set_listing
		@listing = Listing.find(params[:id])
	end

	def listing_params
		params.require(:listing).permit(:address, :unit, :price, :description, :image)
	end

end

gbre_app/app/helpers/agents_helper.rb
module AgentsHelper
end

gbre_app/app/helpers/application_helper.rb
module ApplicationHelper
end

gbre_app/app/helpers/listings_helper.rb
module ListingsHelper
end

gbre_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Green Bay Real Estate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>	

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>	

<%= yield %>

</body>
</html>

gbre_app/app/views/listings/edit.html.erb
<h1 id="head">Green Bay Real Estate</h1>
<div id="menu">
		<ul>
			<li><a href="/">Home</a></li>
			<li><a href="/listings">Listings</a></li>
		</ul>
	</div>

<center>
<h2>Edit Your Listing</h2>
<div id="form"><br>
<%= form_for @listing, url: {action: "update"} do |f| %>
	<%= f.label :address %>:<br>
	<%= f.text_field :address %><br><br>

	<%= f.label :unit %>:<br>
	<%= f.text_field :unit %><br><br>

	<%= f.label :price %>:<br> $
	<%= f.text_field :price %><br><br>

	<%= f.label :description %>:<br>
	<%= f.text_area :description %><br><br>

	<%= f.label :image %>:<br>
	<%= f.file_field :image %><br><br>

	<%= f.submit "Update" %>

<% end %>
</div>

gbre_app/app/views/listings/home.html.erb
<html>
<head>
	<title>Green Bay Real Estate</title>
	<h1 id="head">Green Bay Real Estate</h1>	
<div id="menu">
	<ul>
		<li><a href="/">Home</a></li>
		<li><a href="/listings">Listings</a></li>
	</ul>
</div>
</head>
<body>
	<center><img src="http://www.samueljohnson.com/blog/images/080507.jpg"</center>
</body>
<footer>&copy; Copyright 2015 - Green Bay Real Estate</footer>
</html>

gbre_app/app/views/listings/index.html.erb
<html>
<title>Green Bay Real Estate</title>
<h1 id="head">Green Bay Real Estate</h1>

<div id="menu">
	<ul>
		<li><a href="/">Home</a></li>
		<li><a href="/listings">Listings</a></li>
        <li><a href="/listings/new">New Listing</a></li>
	</ul>
</div>
<center>
<table class="pure-table pure-table-bordered">
    <thead>
        <tr>
        	<th>ID</th>
            <th>Image</th>
            <th>Address</th>
            <th>Unit</th>
            <th>Price</th>
            <th>Description</th>
            <th>Show</th>
        </tr>
    </thead>
    		<% @listings.each do |listing| %>
    <tbody>
        <tr>
            <td><%= listing.id %></td>
            <td><%= image_tag listing.image.url(:thumb) %></td>
            <td><%= listing.address %></td>
            <td><%= listing.unit %></td>
            <td>$<%= listing.price %>.00</td>
            <td><%= listing.description %></td>
            <td><%= link_to "Show", listing %></td>
        </tr>
        	<% end %>
    </tbody>
</table></center>
<footer>&copy; Copyright 2015 - Green Bay Real Estate</footer>
</html>

gbre_app/app/views/listings/new.html.erb
<h1 id="head">Green Bay Real Estate</h1>
<div id="menu">
		<ul>
			<li><a href="/">Home</a></li>
			<li><a href="/listings">Listings</a></li>
		</ul>
	</div>

<center>
<h2>Create a New Listing</h2>

<div id="form"><br>
<%= form_for @listing, url: {action: "create"} do |f| %>
	<%= f.label :address %>:<br>
	<%= f.text_field :address %><br><br>

	<%= f.label :unit %>:<br>
	<%= f.text_field :unit %><br><br>

	<%= f.label :price %>:<br>
	<%= f.text_field :price %><br><br>

	<%= f.label :description %>:<br>
	<%= f.text_area :description %><br><br>

	<%= f.label :image %>:<br>
	<%= f.file_field :image %><br><br>

	<%= f.submit "Create" %>

<% end %>
</div>
</center>

gbre_app/app/views/listings/show.html.erb
<html>
<h1 id="head">Green Bay Real Estate</h1>
<div id="menu">
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/listings">Listings</a></li>
        </ul>
    </div>


<body>
<center><h2>Current Listing</h2></center>

<center><%= link_to 'Back', listings_path %>
<%= link_to 'Edit', edit_listing_path(@listing) %>    
<%= link_to 'Delete', @listing, :method => 'delete' %>
</center><br><br>
<center>
<table class="pure-table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Address</th>
            <th>Unit</th>
            <th>Price</th>
            <th>Description</th>
            <th>Image</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td><%= @listing.id %></td>
            <td><%= @listing.address %></td>
            <td><%= @listing.unit %></td>
            <td>$<%= @listing.price %>.00</td>
            <td><%= @listing.description %></td>
            <td><%= image_tag @listing.image.url(:medium) %></td>
        </tr>
    </tbody><center>
</table>

</body>
</html>